// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/categorias": {
    params: {};
  };
  "/admin/compras": {
    params: {};
  };
  "/admin/productos": {
    params: {};
  };
  "/carrito": {
    params: {};
  };
  "/catalogo": {
    params: {};
  };
  "/catalogo/:id_producto": {
    params: {
      "id_producto": string;
    };
  };
  "/confirmar-email": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/pagar": {
    params: {};
  };
  "/pagar/exito": {
    params: {};
  };
  "/pagar/fallo": {
    params: {};
  };
  "/perfil": {
    params: {};
  };
  "/recuperar-password": {
    params: {};
  };
  "/reenviar-confirmacion": {
    params: {};
  };
  "/registro": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/admin" | "/admin/categorias" | "/admin/compras" | "/admin/productos" | "/carrito" | "/catalogo" | "/catalogo/:id_producto" | "/confirmar-email" | "/login" | "/pagar" | "/pagar/exito" | "/pagar/fallo" | "/perfil" | "/recuperar-password" | "/reenviar-confirmacion" | "/registro";
  };
  "./page.tsx": {
    id: "page";
    page: "/";
  };
  "./admin/page.tsx": {
    id: "admin/page";
    page: "/admin";
  };
  "./admin/categorias/page.tsx": {
    id: "admin/categorias/page";
    page: "/admin/categorias";
  };
  "./admin/compras/page.tsx": {
    id: "admin/compras/page";
    page: "/admin/compras";
  };
  "./admin/productos/page.tsx": {
    id: "admin/productos/page";
    page: "/admin/productos";
  };
  "./carrito/page.tsx": {
    id: "carrito/page";
    page: "/carrito";
  };
  "./catalogo/page.tsx": {
    id: "catalogo/page";
    page: "/catalogo";
  };
  "./catalogo/[id_producto]/page.tsx": {
    id: "catalogo/[id_producto]/page";
    page: "/catalogo/:id_producto";
  };
  "./confirmar-email/page.tsx": {
    id: "confirmar-email/page";
    page: "/confirmar-email";
  };
  "./login/page.tsx": {
    id: "login/page";
    page: "/login";
  };
  "./pagar/page.tsx": {
    id: "pagar/page";
    page: "/pagar";
  };
  "./pagar/exito/page.tsx": {
    id: "pagar/exito/page";
    page: "/pagar/exito";
  };
  "./pagar/fallo/page.tsx": {
    id: "pagar/fallo/page";
    page: "/pagar/fallo";
  };
  "./perfil/page.tsx": {
    id: "perfil/page";
    page: "/perfil";
  };
  "./recuperar-password/page.tsx": {
    id: "recuperar-password/page";
    page: "/recuperar-password";
  };
  "./reenviar-confirmacion/page.tsx": {
    id: "reenviar-confirmacion/page";
    page: "/reenviar-confirmacion";
  };
  "./registro/page.tsx": {
    id: "registro/page";
    page: "/registro";
  };
};